/* -------------------------------------------------------------------------- *
 *                                   OpenMM                                   *
 * -------------------------------------------------------------------------- *
 * This is part of the OpenMM molecular simulation toolkit originating from   *
 * Simbios, the NIH National Center for Physics-Based Simulation of           *
 * Biological Structures at Stanford, funded under the NIH Roadmap for        *
 * Medical Research, grant U54 GM072970. See https://simtk.org.               *
 *                                                                            *
 * Portions copyright (c) 2018 Stanford University and the Authors.           *
 * Authors: Peter Eastman                                                     *
 * Contributors:                                                              *
 *                                                                            *
 * Permission is hereby granted, free of charge, to any person obtaining a    *
 * copy of this software and associated documentation files (the "Software"), *
 * to deal in the Software without restriction, including without limitation  *
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,   *
 * and/or sell copies of the Software, and to permit persons to whom the      *
 * Software is furnished to do so, subject to the following conditions:       *
 *                                                                            *
 * The above copyright notice and this permission notice shall be included in *
 * all copies or substantial portions of the Software.                        *
 *                                                                            *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR *
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   *
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    *
 * THE AUTHORS, CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,    *
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR      *
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE  *
 * USE OR OTHER DEALINGS IN THE SOFTWARE.                                     *
 * -------------------------------------------------------------------------- */

#include "CudaNapShiftKernelSources.h"

using namespace NapShiftPlugin;
using namespace std;

const string CudaNapShiftKernelSources::napshiftForce = "//TODO: actually include openmm/platforms/cuda/src/kernels/vectorOps.cu\n"
"/**\n"
" * This file defines vector operations to simplify code elsewhere.\n"
" */\n"
"\n"
"// Versions of make_x() that take a single value and set all components to that.\n"
"\n"
"inline __device__ int2 make_int2(int a) {\n"
"    return make_int2(a, a);\n"
"}\n"
"\n"
"inline __device__ int3 make_int3(int a) {\n"
"    return make_int3(a, a, a);\n"
"}\n"
"\n"
"inline __device__ int4 make_int4(int a) {\n"
"    return make_int4(a, a, a, a);\n"
"}\n"
"\n"
"inline __device__ float2 make_float2(float a) {\n"
"    return make_float2(a, a);\n"
"}\n"
"\n"
"inline __device__ float3 make_float3(float a) {\n"
"    return make_float3(a, a, a);\n"
"}\n"
"\n"
"inline __device__ float4 make_float4(float a) {\n"
"    return make_float4(a, a, a, a);\n"
"}\n"
"\n"
"inline __device__ double2 make_double2(double a) {\n"
"    return make_double2(a, a);\n"
"}\n"
"\n"
"inline __device__ double3 make_double3(double a) {\n"
"    return make_double3(a, a, a);\n"
"}\n"
"\n"
"inline __device__ double4 make_double4(double a) {\n"
"    return make_double4(a, a, a, a);\n"
"}\n"
"\n"
"// Negate a vector.\n"
"\n"
"inline __device__ int2 operator-(int2 a) {\n"
"    return make_int2(-a.x, -a.y);\n"
"}\n"
"\n"
"inline __device__ int3 operator-(int3 a) {\n"
"    return make_int3(-a.x, -a.y, -a.z);\n"
"}\n"
"\n"
"inline __device__ int4 operator-(int4 a) {\n"
"    return make_int4(-a.x, -a.y, -a.z, -a.w);\n"
"}\n"
"\n"
"inline __device__ float2 operator-(float2 a) {\n"
"    return make_float2(-a.x, -a.y);\n"
"}\n"
"\n"
"inline __device__ float3 operator-(float3 a) {\n"
"    return make_float3(-a.x, -a.y, -a.z);\n"
"}\n"
"\n"
"inline __device__ float4 operator-(float4 a) {\n"
"    return make_float4(-a.x, -a.y, -a.z, -a.w);\n"
"}\n"
"\n"
"inline __device__ double2 operator-(double2 a) {\n"
"    return make_double2(-a.x, -a.y);\n"
"}\n"
"\n"
"inline __device__ double3 operator-(double3 a) {\n"
"    return make_double3(-a.x, -a.y, -a.z);\n"
"}\n"
"\n"
"inline __device__ double4 operator-(double4 a) {\n"
"    return make_double4(-a.x, -a.y, -a.z, -a.w);\n"
"}\n"
"\n"
"// Add two vectors.\n"
"\n"
"inline __device__ int2 operator+(int2 a, int2 b) {\n"
"    return make_int2(a.x+b.x, a.y+b.y);\n"
"}\n"
"\n"
"inline __device__ int3 operator+(int3 a, int3 b) {\n"
"    return make_int3(a.x+b.x, a.y+b.y, a.z+b.z);\n"
"}\n"
"\n"
"inline __device__ int4 operator+(int4 a, int4 b) {\n"
"    return make_int4(a.x+b.x, a.y+b.y, a.z+b.z, a.w+b.w);\n"
"}\n"
"\n"
"inline __device__ float2 operator+(float2 a, float2 b) {\n"
"    return make_float2(a.x+b.x, a.y+b.y);\n"
"}\n"
"\n"
"inline __device__ float3 operator+(float3 a, float3 b) {\n"
"    return make_float3(a.x+b.x, a.y+b.y, a.z+b.z);\n"
"}\n"
"\n"
"inline __device__ float4 operator+(float4 a, float4 b) {\n"
"    return make_float4(a.x+b.x, a.y+b.y, a.z+b.z, a.w+b.w);\n"
"}\n"
"\n"
"inline __device__ double2 operator+(double2 a, double2 b) {\n"
"    return make_double2(a.x+b.x, a.y+b.y);\n"
"}\n"
"\n"
"inline __device__ double3 operator+(double3 a, double3 b) {\n"
"    return make_double3(a.x+b.x, a.y+b.y, a.z+b.z);\n"
"}\n"
"\n"
"inline __device__ double4 operator+(double4 a, double4 b) {\n"
"    return make_double4(a.x+b.x, a.y+b.y, a.z+b.z, a.w+b.w);\n"
"}\n"
"\n"
"// Subtract two vectors.\n"
"\n"
"inline __device__ int2 operator-(int2 a, int2 b) {\n"
"    return make_int2(a.x-b.x, a.y-b.y);\n"
"}\n"
"\n"
"inline __device__ int3 operator-(int3 a, int3 b) {\n"
"    return make_int3(a.x-b.x, a.y-b.y, a.z-b.z);\n"
"}\n"
"\n"
"inline __device__ int4 operator-(int4 a, int4 b) {\n"
"    return make_int4(a.x-b.x, a.y-b.y, a.z-b.z, a.w-b.w);\n"
"}\n"
"\n"
"inline __device__ float2 operator-(float2 a, float2 b) {\n"
"    return make_float2(a.x-b.x, a.y-b.y);\n"
"}\n"
"\n"
"inline __device__ float3 operator-(float3 a, float3 b) {\n"
"    return make_float3(a.x-b.x, a.y-b.y, a.z-b.z);\n"
"}\n"
"\n"
"inline __device__ float4 operator-(float4 a, float4 b) {\n"
"    return make_float4(a.x-b.x, a.y-b.y, a.z-b.z, a.w-b.w);\n"
"}\n"
"\n"
"inline __device__ double2 operator-(double2 a, double2 b) {\n"
"    return make_double2(a.x-b.x, a.y-b.y);\n"
"}\n"
"\n"
"inline __device__ double3 operator-(double3 a, double3 b) {\n"
"    return make_double3(a.x-b.x, a.y-b.y, a.z-b.z);\n"
"}\n"
"\n"
"inline __device__ double4 operator-(double4 a, double4 b) {\n"
"    return make_double4(a.x-b.x, a.y-b.y, a.z-b.z, a.w-b.w);\n"
"}\n"
"\n"
"// Multiply two vectors.\n"
"\n"
"inline __device__ int2 operator*(int2 a, int2 b) {\n"
"    return make_int2(a.x*b.x, a.y*b.y);\n"
"}\n"
"\n"
"inline __device__ int3 operator*(int3 a, int3 b) {\n"
"    return make_int3(a.x*b.x, a.y*b.y, a.z*b.z);\n"
"}\n"
"\n"
"inline __device__ int4 operator*(int4 a, int4 b) {\n"
"    return make_int4(a.x*b.x, a.y*b.y, a.z*b.z, a.w*b.w);\n"
"}\n"
"\n"
"inline __device__ float2 operator*(float2 a, float2 b) {\n"
"    return make_float2(a.x*b.x, a.y*b.y);\n"
"}\n"
"\n"
"inline __device__ float3 operator*(float3 a, float3 b) {\n"
"    return make_float3(a.x*b.x, a.y*b.y, a.z*b.z);\n"
"}\n"
"\n"
"inline __device__ float4 operator*(float4 a, float4 b) {\n"
"    return make_float4(a.x*b.x, a.y*b.y, a.z*b.z, a.w*b.w);\n"
"}\n"
"\n"
"inline __device__ double2 operator*(double2 a, double2 b) {\n"
"    return make_double2(a.x*b.x, a.y*b.y);\n"
"}\n"
"\n"
"inline __device__ double3 operator*(double3 a, double3 b) {\n"
"    return make_double3(a.x*b.x, a.y*b.y, a.z*b.z);\n"
"}\n"
"\n"
"inline __device__ double4 operator*(double4 a, double4 b) {\n"
"    return make_double4(a.x*b.x, a.y*b.y, a.z*b.z, a.w*b.w);\n"
"}\n"
"\n"
"// Divide two vectors.\n"
"\n"
"inline __device__ int2 operator/(int2 a, int2 b) {\n"
"    return make_int2(a.x/b.x, a.y/b.y);\n"
"}\n"
"\n"
"inline __device__ int3 operator/(int3 a, int3 b) {\n"
"    return make_int3(a.x/b.x, a.y/b.y, a.z/b.z);\n"
"}\n"
"\n"
"inline __device__ int4 operator/(int4 a, int4 b) {\n"
"    return make_int4(a.x/b.x, a.y/b.y, a.z/b.z, a.w/b.w);\n"
"}\n"
"\n"
"inline __device__ float2 operator/(float2 a, float2 b) {\n"
"    return make_float2(a.x/b.x, a.y/b.y);\n"
"}\n"
"\n"
"inline __device__ float3 operator/(float3 a, float3 b) {\n"
"    return make_float3(a.x/b.x, a.y/b.y, a.z/b.z);\n"
"}\n"
"\n"
"inline __device__ float4 operator/(float4 a, float4 b) {\n"
"    return make_float4(a.x/b.x, a.y/b.y, a.z/b.z, a.w/b.w);\n"
"}\n"
"\n"
"inline __device__ double2 operator/(double2 a, double2 b) {\n"
"    return make_double2(a.x/b.x, a.y/b.y);\n"
"}\n"
"\n"
"inline __device__ double3 operator/(double3 a, double3 b) {\n"
"    return make_double3(a.x/b.x, a.y/b.y, a.z/b.z);\n"
"}\n"
"\n"
"inline __device__ double4 operator/(double4 a, double4 b) {\n"
"    return make_double4(a.x/b.x, a.y/b.y, a.z/b.z, a.w/b.w);\n"
"}\n"
"\n"
"// += operator\n"
"\n"
"inline __device__ void operator+=(int2& a, int2 b) {\n"
"    a.x += b.x; a.y += b.y;\n"
"}\n"
"\n"
"inline __device__ void operator+=(int3& a, int3 b) {\n"
"    a.x += b.x; a.y += b.y; a.z += b.z;\n"
"}\n"
"\n"
"inline __device__ void operator+=(int4& a, int4 b) {\n"
"    a.x += b.x; a.y += b.y; a.z += b.z; a.w += b.w;\n"
"}\n"
"\n"
"inline __device__ void operator+=(float2& a, float2 b) {\n"
"    a.x += b.x; a.y += b.y;\n"
"}\n"
"\n"
"inline __device__ void operator+=(float3& a, float3 b) {\n"
"    a.x += b.x; a.y += b.y; a.z += b.z;\n"
"}\n"
"\n"
"inline __device__ void operator+=(float4& a, float4 b) {\n"
"    a.x += b.x; a.y += b.y; a.z += b.z; a.w += b.w;\n"
"}\n"
"\n"
"inline __device__ void operator+=(double2& a, double2 b) {\n"
"    a.x += b.x; a.y += b.y;\n"
"}\n"
"\n"
"inline __device__ void operator+=(double3& a, double3 b) {\n"
"    a.x += b.x; a.y += b.y; a.z += b.z;\n"
"}\n"
"\n"
"inline __device__ void operator+=(double4& a, double4 b) {\n"
"    a.x += b.x; a.y += b.y; a.z += b.z; a.w += b.w;\n"
"}\n"
"\n"
"// -= operator\n"
"\n"
"inline __device__ void operator-=(int2& a, int2 b) {\n"
"    a.x -= b.x; a.y -= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator-=(int3& a, int3 b) {\n"
"    a.x -= b.x; a.y -= b.y; a.z -= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator-=(int4& a, int4 b) {\n"
"    a.x -= b.x; a.y -= b.y; a.z -= b.z; a.w -= b.w;\n"
"}\n"
"\n"
"inline __device__ void operator-=(float2& a, float2 b) {\n"
"    a.x -= b.x; a.y -= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator-=(float3& a, float3 b) {\n"
"    a.x -= b.x; a.y -= b.y; a.z -= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator-=(float4& a, float4 b) {\n"
"    a.x -= b.x; a.y -= b.y; a.z -= b.z; a.w -= b.w;\n"
"}\n"
"\n"
"inline __device__ void operator-=(double2& a, double2 b) {\n"
"    a.x -= b.x; a.y -= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator-=(double3& a, double3 b) {\n"
"    a.x -= b.x; a.y -= b.y; a.z -= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator-=(double4& a, double4 b) {\n"
"    a.x -= b.x; a.y -= b.y; a.z -= b.z; a.w -= b.w;\n"
"}\n"
"\n"
"// *= operator\n"
"\n"
"inline __device__ void operator*=(int2& a, int2 b) {\n"
"    a.x *= b.x; a.y *= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator*=(int3& a, int3 b) {\n"
"    a.x *= b.x; a.y *= b.y; a.z *= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator*=(int4& a, int4 b) {\n"
"    a.x *= b.x; a.y *= b.y; a.z *= b.z; a.w *= b.w;\n"
"}\n"
"\n"
"inline __device__ void operator*=(float2& a, float2 b) {\n"
"    a.x *= b.x; a.y *= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator*=(float3& a, float3 b) {\n"
"    a.x *= b.x; a.y *= b.y; a.z *= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator*=(float4& a, float4 b) {\n"
"    a.x *= b.x; a.y *= b.y; a.z *= b.z; a.w *= b.w;\n"
"}\n"
"\n"
"inline __device__ void operator*=(double2& a, double2 b) {\n"
"    a.x *= b.x; a.y *= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator*=(double3& a, double3 b) {\n"
"    a.x *= b.x; a.y *= b.y; a.z *= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator*=(double4& a, double4 b) {\n"
"    a.x *= b.x; a.y *= b.y; a.z *= b.z; a.w *= b.w;\n"
"}\n"
"\n"
"// /= operator\n"
"\n"
"inline __device__ void operator/=(int2& a, int2 b) {\n"
"    a.x /= b.x; a.y /= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator/=(int3& a, int3 b) {\n"
"    a.x /= b.x; a.y /= b.y; a.z /= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator/=(int4& a, int4 b) {\n"
"    a.x /= b.x; a.y /= b.y; a.z /= b.z; a.w /= b.w;\n"
"}\n"
"\n"
"inline __device__ void operator/=(float2& a, float2 b) {\n"
"    a.x /= b.x; a.y /= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator/=(float3& a, float3 b) {\n"
"    a.x /= b.x; a.y /= b.y; a.z /= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator/=(float4& a, float4 b) {\n"
"    a.x /= b.x; a.y /= b.y; a.z /= b.z; a.w /= b.w;\n"
"}\n"
"\n"
"inline __device__ void operator/=(double2& a, double2 b) {\n"
"    a.x /= b.x; a.y /= b.y;\n"
"}\n"
"\n"
"inline __device__ void operator/=(double3& a, double3 b) {\n"
"    a.x /= b.x; a.y /= b.y; a.z /= b.z;\n"
"}\n"
"\n"
"inline __device__ void operator/=(double4& a, double4 b) {\n"
"    a.x /= b.x; a.y /= b.y; a.z /= b.z; a.w /= b.w;\n"
"}\n"
"\n"
"// Multiply a vector by a constant.\n"
"\n"
"inline __device__ int2 operator*(int2 a, int b) {\n"
"    return make_int2(a.x*b, a.y*b);\n"
"}\n"
"\n"
"inline __device__ int3 operator*(int3 a, int b) {\n"
"    return make_int3(a.x*b, a.y*b, a.z*b);\n"
"}\n"
"\n"
"inline __device__ int4 operator*(int4 a, int b) {\n"
"    return make_int4(a.x*b, a.y*b, a.z*b, a.w*b);\n"
"}\n"
"\n"
"inline __device__ int2 operator*(int a, int2 b) {\n"
"    return make_int2(a*b.x, a*b.y);\n"
"}\n"
"\n"
"inline __device__ int3 operator*(int a, int3 b) {\n"
"    return make_int3(a*b.x, a*b.y, a*b.z);\n"
"}\n"
"\n"
"inline __device__ int4 operator*(int a, int4 b) {\n"
"    return make_int4(a*b.x, a*b.y, a*b.z, a*b.w);\n"
"}\n"
"\n"
"inline __device__ float2 operator*(float2 a, float b) {\n"
"    return make_float2(a.x*b, a.y*b);\n"
"}\n"
"\n"
"inline __device__ float3 operator*(float3 a, float b) {\n"
"    return make_float3(a.x*b, a.y*b, a.z*b);\n"
"}\n"
"\n"
"inline __device__ float4 operator*(float4 a, float b) {\n"
"    return make_float4(a.x*b, a.y*b, a.z*b, a.w*b);\n"
"}\n"
"\n"
"inline __device__ float2 operator*(float a, float2 b) {\n"
"    return make_float2(a*b.x, a*b.y);\n"
"}\n"
"\n"
"inline __device__ float3 operator*(float a, float3 b) {\n"
"    return make_float3(a*b.x, a*b.y, a*b.z);\n"
"}\n"
"\n"
"inline __device__ float4 operator*(float a, float4 b) {\n"
"    return make_float4(a*b.x, a*b.y, a*b.z, a*b.w);\n"
"}\n"
"\n"
"inline __device__ double2 operator*(double2 a, double b) {\n"
"    return make_double2(a.x*b, a.y*b);\n"
"}\n"
"\n"
"inline __device__ double3 operator*(double3 a, double b) {\n"
"    return make_double3(a.x*b, a.y*b, a.z*b);\n"
"}\n"
"\n"
"inline __device__ double4 operator*(double4 a, double b) {\n"
"    return make_double4(a.x*b, a.y*b, a.z*b, a.w*b);\n"
"}\n"
"\n"
"inline __device__ double2 operator*(double a, double2 b) {\n"
"    return make_double2(a*b.x, a*b.y);\n"
"}\n"
"\n"
"inline __device__ double3 operator*(double a, double3 b) {\n"
"    return make_double3(a*b.x, a*b.y, a*b.z);\n"
"}\n"
"\n"
"inline __device__ double4 operator*(double a, double4 b) {\n"
"    return make_double4(a*b.x, a*b.y, a*b.z, a*b.w);\n"
"}\n"
"\n"
"// Divide a vector by a constant.\n"
"\n"
"inline __device__ int2 operator/(int2 a, int b) {\n"
"    return make_int2(a.x/b, a.y/b);\n"
"}\n"
"\n"
"inline __device__ int3 operator/(int3 a, int b) {\n"
"    return make_int3(a.x/b, a.y/b, a.z/b);\n"
"}\n"
"\n"
"inline __device__ int4 operator/(int4 a, int b) {\n"
"    return make_int4(a.x/b, a.y/b, a.z/b, a.w/b);\n"
"}\n"
"\n"
"inline __device__ float2 operator/(float2 a, float b) {\n"
"    float scale = 1.0f/b;\n"
"    return a*scale;\n"
"}\n"
"\n"
"inline __device__ float3 operator/(float3 a, float b) {\n"
"    float scale = 1.0f/b;\n"
"    return a*scale;\n"
"}\n"
"\n"
"inline __device__ float4 operator/(float4 a, float b) {\n"
"    float scale = 1.0f/b;\n"
"    return a*scale;\n"
"}\n"
"\n"
"inline __device__ double2 operator/(double2 a, double b) {\n"
"    double scale = 1.0/b;\n"
"    return a*scale;\n"
"}\n"
"\n"
"inline __device__ double3 operator/(double3 a, double b) {\n"
"    double scale = 1.0/b;\n"
"    return a*scale;\n"
"}\n"
"\n"
"inline __device__ double4 operator/(double4 a, double b) {\n"
"    double scale = 1.0/b;\n"
"    return a*scale;\n"
"}\n"
"\n"
"// *= operator (multiply vector by constant)\n"
"\n"
"inline __device__ void operator*=(int2& a, int b) {\n"
"    a.x *= b; a.y *= b;\n"
"}\n"
"\n"
"inline __device__ void operator*=(int3& a, int b) {\n"
"    a.x *= b; a.y *= b; a.z *= b;\n"
"}\n"
"\n"
"inline __device__ void operator*=(int4& a, int b) {\n"
"    a.x *= b; a.y *= b; a.z *= b; a.w *= b;\n"
"}\n"
"\n"
"inline __device__ void operator*=(float2& a, float b) {\n"
"    a.x *= b; a.y *= b;\n"
"}\n"
"\n"
"inline __device__ void operator*=(float3& a, float b) {\n"
"    a.x *= b; a.y *= b; a.z *= b;\n"
"}\n"
"\n"
"inline __device__ void operator*=(float4& a, float b) {\n"
"    a.x *= b; a.y *= b; a.z *= b; a.w *= b;\n"
"}\n"
"\n"
"inline __device__ void operator*=(double2& a, double b) {\n"
"    a.x *= b; a.y *= b;\n"
"}\n"
"\n"
"inline __device__ void operator*=(double3& a, double b) {\n"
"    a.x *= b; a.y *= b; a.z *= b;\n"
"}\n"
"\n"
"inline __device__ void operator*=(double4& a, double b) {\n"
"    a.x *= b; a.y *= b; a.z *= b; a.w *= b;\n"
"}\n"
"\n"
"// Dot product\n"
"\n"
"inline __device__ float dot(float3 a, float3 b) {\n"
"    return a.x*b.x+a.y*b.y+a.z*b.z;\n"
"}\n"
"\n"
"inline __device__ double dot(double3 a, double3 b) {\n"
"    return a.x*b.x+a.y*b.y+a.z*b.z;\n"
"}\n"
"\n"
"// Cross product\n"
"\n"
"inline __device__ float3 cross(float3 a, float3 b) {\n"
"    return make_float3(a.y*b.z-a.z*b.y, a.z*b.x-a.x*b.z, a.x*b.y-a.y*b.x);\n"
"}\n"
"\n"
"inline __device__ float4 cross(float4 a, float4 b) {\n"
"    return make_float4(a.y*b.z-a.z*b.y, a.z*b.x-a.x*b.z, a.x*b.y-a.y*b.x, 0.0f);\n"
"}\n"
"\n"
"inline __device__ double3 cross(double3 a, double3 b) {\n"
"    return make_double3(a.y*b.z-a.z*b.y, a.z*b.x-a.x*b.z, a.x*b.y-a.y*b.x);\n"
"}\n"
"\n"
"inline __device__ double4 cross(double4 a, double4 b) {\n"
"    return make_double4(a.y*b.z-a.z*b.y, a.z*b.x-a.x*b.z, a.x*b.y-a.y*b.x, 0.0);\n"
"}\n"
"\n"
"// Normalize a vector\n"
"\n"
"inline __device__ float2 normalize(float2 a) {\n"
"    return a*rsqrtf(a.x*a.x+a.y*a.y);\n"
"}\n"
"\n"
"inline __device__ float3 normalize(float3 a) {\n"
"    return a*rsqrtf(a.x*a.x+a.y*a.y+a.z*a.z);\n"
"}\n"
"\n"
"inline __device__ float4 normalize(float4 a) {\n"
"    return a*rsqrtf(a.x*a.x+a.y*a.y+a.z*a.z+a.w*a.w);\n"
"}\n"
"\n"
"inline __device__ double2 normalize(double2 a) {\n"
"    return a*rsqrt(a.x*a.x+a.y*a.y);\n"
"}\n"
"\n"
"inline __device__ double3 normalize(double3 a) {\n"
"    return a*rsqrt(a.x*a.x+a.y*a.y+a.z*a.z);\n"
"}\n"
"\n"
"inline __device__ double4 normalize(double4 a) {\n"
"    return a*rsqrt(a.x*a.x+a.y*a.y+a.z*a.z+a.w*a.w);\n"
"}\n"
"\n"
"extern \"C\" __device__\n"
"real calculateDihedral(int a1, int a2, int a3, int a4, real3* forceOutputs, const int* __restrict__ indexToAtom, const real4* __restrict__ posq, real4 periodicBoxSize, real4 invPeriodicBoxSize) {\n"
"    if ( a1 == -1 || a2 == -1 || a3 == -1 || a4 == -1 ) {\n"
"        return -100;\n"
"    }\n"
"    real4 pos1 = posq[indexToAtom[a1]];\n"
"    real4 pos2 = posq[indexToAtom[a2]];\n"
"    real4 pos3 = posq[indexToAtom[a3]];\n"
"    real4 pos4 = posq[indexToAtom[a4]];\n"
"\n"
"    const real PI = (real) 3.14159265358979323846;\n"
"    real3 v0 = make_real3(pos1.x-pos2.x, pos1.y-pos2.y, pos1.z-pos2.z);\n"
"    real3 v1 = make_real3(pos3.x-pos2.x, pos3.y-pos2.y, pos3.z-pos2.z);\n"
"    real3 v2 = make_real3(pos3.x-pos4.x, pos3.y-pos4.y, pos3.z-pos4.z);\n"
"    #if APPLY_PERIODIC\n"
"    APPLY_PERIODIC_TO_DELTA(v0)\n"
"    APPLY_PERIODIC_TO_DELTA(v1)\n"
"    APPLY_PERIODIC_TO_DELTA(v2)\n"
"    #endif\n"
"    real3 cp0 = cross(v0, v1);\n"
"    real3 cp1 = cross(v1, v2);\n"
"    real cosangle = dot(normalize(cp0), normalize(cp1));\n"
"    real theta;\n"
"    if (cosangle > 0.99f || cosangle < -0.99f) {\n"
"        real3 cross_prod = cross(cp0, cp1);\n"
"        real scale = dot(cp0, cp0)*dot(cp1, cp1);\n"
"        theta = ASIN(SQRT(dot(cross_prod, cross_prod)/scale));\n"
"        if (cosangle < 0)\n"
"            theta = PI-theta;\n"
"    } else {\n"
"        theta = ACOS(cosangle);\n"
"    }\n"
"    theta = (dot(v0, cp1) >= 0 ? theta : -theta);\n"
"    \n"
"    real normCross1 = dot(cp0, cp0);\n"
"    real normSqrBC = dot(v1, v1);\n"
"    real normBC = SQRT(normSqrBC);\n"
"    real normCross2 = dot(cp1, cp1);\n"
"    real dp = RECIP(normSqrBC);\n"
"    real4 ff = make_real4((-normBC)/normCross1, dot(v0, v1)*dp, dot(v2, v1)*dp, (normBC)/normCross2);\n"
"    \n"
"    real3 force1 = ff.x*cp0;\n"
"    real3 force4 = ff.w*cp1;\n"
"    real3 s = ff.y*force1 - ff.z*force4;\n"
"    real3 force2 = s-force1;\n"
"    real3 force3 = -s-force4;\n"
"\n"
"    forceOutputs[0] = force1;\n"
"    forceOutputs[1] = force2;\n"
"    forceOutputs[2] = force3;\n"
"    forceOutputs[3] = force4;\n"
"\n"
"    return theta;\n"
"}\n"
"\n"
"extern \"C\" __device__\n"
"real calculateAngle(int a1, int a2, int a3, real3* forceOutputs, const int* __restrict__ indexToAtom, const real4* __restrict__ posq, real4 periodicBoxSize, real4 invPeriodicBoxSize) {\n"
"    if ( a1 == -1 || a2 == -1 || a3 == -1) {\n"
"        return -100;\n"
"    }\n"
"\n"
"    real4 pos1 = posq[indexToAtom[a1]];\n"
"    real4 pos2 = posq[indexToAtom[a2]];\n"
"    real4 pos3 = posq[indexToAtom[a3]];\n"
"\n"
"    real3 v0 = make_real3(pos2.x-pos1.x, pos2.y-pos1.y, pos2.z-pos1.z);\n"
"    real3 v1 = make_real3(pos2.x-pos3.x, pos2.y-pos3.y, pos2.z-pos3.z);\n"
"    \n"
"    #if APPLY_PERIODIC\n"
"    APPLY_PERIODIC_TO_DELTA(v0)\n"
"    APPLY_PERIODIC_TO_DELTA(v1)\n"
"    #endif\n"
"    real3 cp = cross(v0, v1);\n"
"    real rp = cp.x*cp.x + cp.y*cp.y + cp.z*cp.z;\n"
"    rp = max(SQRT(rp), (real) 1.0e-06f);\n"
"    real r21 = v0.x*v0.x + v0.y*v0.y + v0.z*v0.z;\n"
"    real r23 = v1.x*v1.x + v1.y*v1.y + v1.z*v1.z;\n"
"    real dot = v0.x*v1.x + v0.y*v1.y + v0.z*v1.z;\n"
"    real cosine = min(max(dot*RSQRT(r21*r23), (real) -1), (real) 1);\n"
"    real theta = ACOS(cosine);\n"
"\n"
"    real3 force1 = cross(v0, cp)*(1/(r21*rp));\n"
"    real3 force3 = cross(cp, v1)*(1/(r23*rp));\n"
"    real3 force2 = -force1-force3;\n"
"    \n"
"    forceOutputs[0] = force1;\n"
"    forceOutputs[1] = force2;\n"
"    forceOutputs[2] = force3;\n"
"\n"
"    return theta;\n"
"}\n"
"\n"
"extern \"C\" __global__\n"
"void resolveAngle(real* inputTensor,\n"
"                  real* __restrict__ angleForceArray,\n"
"                  const int* particlesIndices,\n"
"                  const int* indexToAtom,\n"
"                  const real4* posq,\n"
"                  const int numPeptides,\n"
"                  const int numAnglesPerPeptide,\n"
"                  real4 periodicBoxSize,\n"
"                  real4 invPeriodicBoxSize){\n"
"                    \n"
"    for (int angle_idx = blockIdx.x*blockDim.x+threadIdx.x; angle_idx < numPeptides*numAnglesPerPeptide; angle_idx += blockDim.x*gridDim.x) { \n"
"\n"
"        int peptide = floor(float(angle_idx) / float(numAnglesPerPeptide));\n"
"        int angleNum = angle_idx - peptide*numAnglesPerPeptide;\n"
"        real angle = 0;\n"
"        real3 angle_force[4] = {0,0,0,0};\n"
"        if (angleNum < 2 || numAnglesPerPeptide == 4){ //always calculate diheds in all-atom format\n"
"            angle = calculateDihedral(particlesIndices[4*angle_idx+0],\n"
"                              particlesIndices[4*angle_idx+1],\n"
"                              particlesIndices[4*angle_idx+2],\n"
"                              particlesIndices[4*angle_idx+3],\n"
"                              angle_force, indexToAtom, posq, periodicBoxSize, invPeriodicBoxSize);\n"
"        } else {\n"
"            angle = calculateAngle(particlesIndices[4*angle_idx+0],\n"
"                              particlesIndices[4*angle_idx+1],\n"
"                              particlesIndices[4*angle_idx+2],\n"
"                              angle_force, indexToAtom, posq, periodicBoxSize, invPeriodicBoxSize);\n"
"        }\n"
"        real sinAngle = angle == -100 ? 0 : SIN(angle);\n"
"        real cosAngle = angle == -100 ? 0 : COS(angle);\n"
"\n"
"        int idx_left = 3*(2*numAnglesPerPeptide+22)*(peptide-1)+66+4*numAnglesPerPeptide+2*angleNum;\n"
"        int idx_center = 3*(2*numAnglesPerPeptide+22)*(peptide)+44+2*numAnglesPerPeptide+2*angleNum;\n"
"        int idx_right = 3*(2*numAnglesPerPeptide+22)*(peptide+1)+22+2*angleNum;\n"
"        \n"
"        //trying to set all three entries for this peptide at once precludes contiguous access... what would be faster?\n"
"        if (peptide > 0) {\n"
"            inputTensor[idx_left] = sinAngle;\n"
"            inputTensor[idx_left+1] = cosAngle;\n"
"\n"
"        }\n"
"        inputTensor[idx_center] = sinAngle;\n"
"        inputTensor[idx_center+1] = cosAngle;\n"
"        if (peptide < numPeptides-1) {\n"
"            inputTensor[idx_right] = sinAngle;\n"
"            inputTensor[idx_right+1] = cosAngle;\n"
"        }\n"
"\n"
"        int sin_force_idx_left = 3*24*numAnglesPerPeptide*(peptide-1)+2*24*numAnglesPerPeptide+12*2*angleNum;\n"
"        int sin_force_idx_center = 3*24*numAnglesPerPeptide*(peptide)+24*numAnglesPerPeptide+12*2*angleNum;\n"
"        int sin_force_idx_right = 3*24*numAnglesPerPeptide*(peptide+1)+12*2*angleNum;\n"
"\n"
"        int cos_force_idx_left = 3*24*numAnglesPerPeptide*(peptide-1)+2*24*numAnglesPerPeptide+12*(2*angleNum+1);\n"
"        int cos_force_idx_center = 3*24*numAnglesPerPeptide*(peptide)+24*numAnglesPerPeptide+12*(2*angleNum+1);\n"
"        int cos_force_idx_right = 3*24*numAnglesPerPeptide*(peptide+1)+12*(2*angleNum+1);\n"
"\n"
"        real3 sinForce;\n"
"        real3 cosForce;\n"
"\n"
"        for (int j=0;j<4;j++){\n"
"            sinForce = cosAngle * angle_force[j];\n"
"            if (peptide > 0) {\n"
"                angleForceArray[sin_force_idx_left+3*j] = sinForce.x;\n"
"                angleForceArray[sin_force_idx_left+3*j+1] = sinForce.y;\n"
"                angleForceArray[sin_force_idx_left+3*j+2] = sinForce.z;\n"
"            }\n"
"            angleForceArray[sin_force_idx_center+3*j] = sinForce.x;\n"
"            angleForceArray[sin_force_idx_center+3*j+1] = sinForce.y;\n"
"            angleForceArray[sin_force_idx_center+3*j+2] = sinForce.z;\n"
"            if (peptide < numPeptides-1) {\n"
"                angleForceArray[sin_force_idx_right+3*j] = sinForce.x;\n"
"                angleForceArray[sin_force_idx_right+3*j+1] = sinForce.y;\n"
"                angleForceArray[sin_force_idx_right+3*j+2] = sinForce.z;\n"
"            }\n"
"        }\n"
"        for (int j=0;j<4;j++){\n"
"            cosForce = -sinAngle * angle_force[j];\n"
"            if (peptide > 0) {\n"
"                angleForceArray[cos_force_idx_left+3*j] = cosForce.x;\n"
"                angleForceArray[cos_force_idx_left+3*j+1] = cosForce.y;\n"
"                angleForceArray[cos_force_idx_left+3*j+2] = cosForce.z;\n"
"            }\n"
"            angleForceArray[cos_force_idx_center+3*j] = cosForce.x;\n"
"            angleForceArray[cos_force_idx_center+3*j+1] = cosForce.y;\n"
"            angleForceArray[cos_force_idx_center+3*j+2] = cosForce.z;\n"
"            if (peptide < numPeptides-1) {\n"
"                angleForceArray[cos_force_idx_right+3*j] = cosForce.x;\n"
"                angleForceArray[cos_force_idx_right+3*j+1] = cosForce.y;\n"
"                angleForceArray[cos_force_idx_right+3*j+2] = cosForce.z;\n"
"            }\n"
"        }\n"
"    }\n"
"}\n"
"\n"
"extern \"C\" __global__\n"
"void accumulateParticleForces(const real* __restrict__ NapShiftForces,\n"
"                              const real* __restrict__ angleForces,\n"
"                              const int* __restrict__ perParticleForceIndices,\n"
"                              const int* __restrict__ NapShiftParticleIndices,\n"
"                              int maxForcesPerParticle,\n"
"                              int numNapShiftParticles,\n"
"                              const int* __restrict__ indexToAtom,\n"
"                              long long* __restrict__ forceBuffers,\n"
"                              int paddedNumAtoms) {  \n"
"    for (int particleNum = blockIdx.x*blockDim.x+threadIdx.x; particleNum < numNapShiftParticles; particleNum += blockDim.x*gridDim.x) {\n"
"        int particle = NapShiftParticleIndices[particleNum];\n"
"        int atom = indexToAtom[particle];\n"
"        int forceIndex = 0;\n"
"        real perParticleForceX = 0;\n"
"        real perParticleForceY = 0;\n"
"        real perParticleForceZ = 0;\n"
"        for (int i=0; i < maxForcesPerParticle; i++) {\n"
"            forceIndex = perParticleForceIndices[particleNum*maxForcesPerParticle + i];\n"
"            if (forceIndex < 0) {\n"
"                break;\n"
"            }\n"
"            perParticleForceX += (NapShiftForces[3*forceIndex] * angleForces[3*forceIndex]);\n"
"            perParticleForceY += (NapShiftForces[3*forceIndex+1] * angleForces[3*forceIndex+1]);\n"
"            perParticleForceZ += (NapShiftForces[3*forceIndex+2] * angleForces[3*forceIndex+2]);\n"
"        }\n"
"        forceBuffers[atom] += (long long) (perParticleForceX*0x100000000);\n"
"        forceBuffers[atom+paddedNumAtoms] += (long long) (perParticleForceY*0x100000000);\n"
"        forceBuffers[atom+2*paddedNumAtoms] += (long long) (perParticleForceZ*0x100000000);\n"
"    }\n"
"}\n"
"\n"
"extern \"C\" __global__\n"
"void swapAtomToIndex(const int* __restrict__ atomToIndex, const int numAtoms, int* __restrict__ indexToAtom) {\n"
"    int k;\n"
"    for (int atom = blockIdx.x*blockDim.x+threadIdx.x; atom < numAtoms; atom += blockDim.x*gridDim.x) {\n"
"        k = atomToIndex[atom];\n"
"        indexToAtom[k] = atom;\n"
"    }\n"
"}\n"
"\n"
"extern \"C\" __global__\n"
"void DownloadCSDifferenceAvgData(real* __restrict__ avgCSTensor,\n"
"                                 const real* downloadedData,\n"
"                                 int numNapShiftParticles) {\n"
"    for (int particle = blockIdx.x*blockDim.x+ threadIdx.x; particle < numNapShiftParticles; particle += blockDim.x*gridDim.x) {\n"
"        avgCSTensor[6*particle+0] = downloadedData[6*particle+0];\n"
"        avgCSTensor[6*particle+1] = downloadedData[6*particle+1];\n"
"        avgCSTensor[6*particle+2] = downloadedData[6*particle+2];\n"
"        avgCSTensor[6*particle+3] = downloadedData[6*particle+3];\n"
"        avgCSTensor[6*particle+4] = downloadedData[6*particle+4];\n"
"        avgCSTensor[6*particle+5] = downloadedData[6*particle+5];\n"
"    }\n"
"}\n"
"";
