name: BuildOpenMMNapShift
channels:
  - conda-forge
dependencies:
  - cmake
  - cuda-toolkit 12.9.1 ha804496_0
  - gxx_linux-64 14.3.0 h310e576_17
  - make
  - cuda-nvcc_linux-64 12.9.86 he0b4e1d_4
  - ocl-icd
  - openmm >=8.1
  - pip
  - pocl
  - pytest
  - python
  - pytorch 2.9.1 cuda129_mkl_py311_hcbd18c7_301
  - swig
  - sysroot_linux-64 2.17
  - libxcrypt