# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.


import sys
if sys.platform == 'win32':
    import os
    import torch
    import openmm
    openmmnapshift_library_path = openmm.version.openmm_library_path

    _path = os.environ['PATH']
    os.environ['PATH'] = r'%(lib)s;%(lib)s\plugins;%(path)s' % {'lib': openmmnapshift_library_path, 'path': _path}

    os.add_dll_directory(openmmnapshift_library_path)




from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _napshiftforce
else:
    import _napshiftforce

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import simtk.openmm
class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _napshiftforce.delete_SwigPyIterator

    def value(self):
        return _napshiftforce.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _napshiftforce.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _napshiftforce.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _napshiftforce.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _napshiftforce.SwigPyIterator_equal(self, x)

    def copy(self):
        return _napshiftforce.SwigPyIterator_copy(self)

    def next(self):
        return _napshiftforce.SwigPyIterator_next(self)

    def __next__(self):
        return _napshiftforce.SwigPyIterator___next__(self)

    def previous(self):
        return _napshiftforce.SwigPyIterator_previous(self)

    def advance(self, n):
        return _napshiftforce.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _napshiftforce.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _napshiftforce.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _napshiftforce.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _napshiftforce.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _napshiftforce.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _napshiftforce.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _napshiftforce:
_napshiftforce.SwigPyIterator_swigregister(SwigPyIterator)
class property_map(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _napshiftforce.property_map_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _napshiftforce.property_map___nonzero__(self)

    def __bool__(self):
        return _napshiftforce.property_map___bool__(self)

    def __len__(self):
        return _napshiftforce.property_map___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _napshiftforce.property_map___getitem__(self, key)

    def __delitem__(self, key):
        return _napshiftforce.property_map___delitem__(self, key)

    def has_key(self, key):
        return _napshiftforce.property_map_has_key(self, key)

    def keys(self):
        return _napshiftforce.property_map_keys(self)

    def values(self):
        return _napshiftforce.property_map_values(self)

    def items(self):
        return _napshiftforce.property_map_items(self)

    def __contains__(self, key):
        return _napshiftforce.property_map___contains__(self, key)

    def key_iterator(self):
        return _napshiftforce.property_map_key_iterator(self)

    def value_iterator(self):
        return _napshiftforce.property_map_value_iterator(self)

    def __setitem__(self, *args):
        return _napshiftforce.property_map___setitem__(self, *args)

    def asdict(self):
        return _napshiftforce.property_map_asdict(self)

    def __init__(self, *args):
        _napshiftforce.property_map_swiginit(self, _napshiftforce.new_property_map(*args))

    def empty(self):
        return _napshiftforce.property_map_empty(self)

    def size(self):
        return _napshiftforce.property_map_size(self)

    def swap(self, v):
        return _napshiftforce.property_map_swap(self, v)

    def begin(self):
        return _napshiftforce.property_map_begin(self)

    def end(self):
        return _napshiftforce.property_map_end(self)

    def rbegin(self):
        return _napshiftforce.property_map_rbegin(self)

    def rend(self):
        return _napshiftforce.property_map_rend(self)

    def clear(self):
        return _napshiftforce.property_map_clear(self)

    def get_allocator(self):
        return _napshiftforce.property_map_get_allocator(self)

    def count(self, x):
        return _napshiftforce.property_map_count(self, x)

    def erase(self, *args):
        return _napshiftforce.property_map_erase(self, *args)

    def find(self, x):
        return _napshiftforce.property_map_find(self, x)

    def lower_bound(self, x):
        return _napshiftforce.property_map_lower_bound(self, x)

    def upper_bound(self, x):
        return _napshiftforce.property_map_upper_bound(self, x)
    __swig_destroy__ = _napshiftforce.delete_property_map

# Register property_map in _napshiftforce:
_napshiftforce.property_map_swigregister(property_map)
class csExp_map(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _napshiftforce.csExp_map_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _napshiftforce.csExp_map___nonzero__(self)

    def __bool__(self):
        return _napshiftforce.csExp_map___bool__(self)

    def __len__(self):
        return _napshiftforce.csExp_map___len__(self)
    def __iter__(self):
        return self.key_iterator()
    def iterkeys(self):
        return self.key_iterator()
    def itervalues(self):
        return self.value_iterator()
    def iteritems(self):
        return self.iterator()

    def __getitem__(self, key):
        return _napshiftforce.csExp_map___getitem__(self, key)

    def __delitem__(self, key):
        return _napshiftforce.csExp_map___delitem__(self, key)

    def has_key(self, key):
        return _napshiftforce.csExp_map_has_key(self, key)

    def keys(self):
        return _napshiftforce.csExp_map_keys(self)

    def values(self):
        return _napshiftforce.csExp_map_values(self)

    def items(self):
        return _napshiftforce.csExp_map_items(self)

    def __contains__(self, key):
        return _napshiftforce.csExp_map___contains__(self, key)

    def key_iterator(self):
        return _napshiftforce.csExp_map_key_iterator(self)

    def value_iterator(self):
        return _napshiftforce.csExp_map_value_iterator(self)

    def __setitem__(self, *args):
        return _napshiftforce.csExp_map___setitem__(self, *args)

    def asdict(self):
        return _napshiftforce.csExp_map_asdict(self)

    def __init__(self, *args):
        _napshiftforce.csExp_map_swiginit(self, _napshiftforce.new_csExp_map(*args))

    def empty(self):
        return _napshiftforce.csExp_map_empty(self)

    def size(self):
        return _napshiftforce.csExp_map_size(self)

    def swap(self, v):
        return _napshiftforce.csExp_map_swap(self, v)

    def begin(self):
        return _napshiftforce.csExp_map_begin(self)

    def end(self):
        return _napshiftforce.csExp_map_end(self)

    def rbegin(self):
        return _napshiftforce.csExp_map_rbegin(self)

    def rend(self):
        return _napshiftforce.csExp_map_rend(self)

    def clear(self):
        return _napshiftforce.csExp_map_clear(self)

    def get_allocator(self):
        return _napshiftforce.csExp_map_get_allocator(self)

    def count(self, x):
        return _napshiftforce.csExp_map_count(self, x)

    def erase(self, *args):
        return _napshiftforce.csExp_map_erase(self, *args)

    def find(self, x):
        return _napshiftforce.csExp_map_find(self, x)

    def lower_bound(self, x):
        return _napshiftforce.csExp_map_lower_bound(self, x)

    def upper_bound(self, x):
        return _napshiftforce.csExp_map_upper_bound(self, x)
    __swig_destroy__ = _napshiftforce.delete_csExp_map

# Register csExp_map in _napshiftforce:
_napshiftforce.csExp_map_swigregister(csExp_map)
class atomVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _napshiftforce.atomVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _napshiftforce.atomVector___nonzero__(self)

    def __bool__(self):
        return _napshiftforce.atomVector___bool__(self)

    def __len__(self):
        return _napshiftforce.atomVector___len__(self)

    def __getslice__(self, i, j):
        return _napshiftforce.atomVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _napshiftforce.atomVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _napshiftforce.atomVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _napshiftforce.atomVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _napshiftforce.atomVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _napshiftforce.atomVector___setitem__(self, *args)

    def pop(self):
        return _napshiftforce.atomVector_pop(self)

    def append(self, x):
        return _napshiftforce.atomVector_append(self, x)

    def empty(self):
        return _napshiftforce.atomVector_empty(self)

    def size(self):
        return _napshiftforce.atomVector_size(self)

    def swap(self, v):
        return _napshiftforce.atomVector_swap(self, v)

    def begin(self):
        return _napshiftforce.atomVector_begin(self)

    def end(self):
        return _napshiftforce.atomVector_end(self)

    def rbegin(self):
        return _napshiftforce.atomVector_rbegin(self)

    def rend(self):
        return _napshiftforce.atomVector_rend(self)

    def clear(self):
        return _napshiftforce.atomVector_clear(self)

    def get_allocator(self):
        return _napshiftforce.atomVector_get_allocator(self)

    def pop_back(self):
        return _napshiftforce.atomVector_pop_back(self)

    def erase(self, *args):
        return _napshiftforce.atomVector_erase(self, *args)

    def __init__(self, *args):
        _napshiftforce.atomVector_swiginit(self, _napshiftforce.new_atomVector(*args))

    def push_back(self, x):
        return _napshiftforce.atomVector_push_back(self, x)

    def front(self):
        return _napshiftforce.atomVector_front(self)

    def back(self):
        return _napshiftforce.atomVector_back(self)

    def assign(self, n, x):
        return _napshiftforce.atomVector_assign(self, n, x)

    def resize(self, *args):
        return _napshiftforce.atomVector_resize(self, *args)

    def insert(self, *args):
        return _napshiftforce.atomVector_insert(self, *args)

    def reserve(self, n):
        return _napshiftforce.atomVector_reserve(self, n)

    def capacity(self):
        return _napshiftforce.atomVector_capacity(self)
    __swig_destroy__ = _napshiftforce.delete_atomVector

# Register atomVector in _napshiftforce:
_napshiftforce.atomVector_swigregister(atomVector)
class NapShiftForce(simtk.openmm.Force):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _napshiftforce.NapShiftForce_swiginit(self, _napshiftforce.new_NapShiftForce(*args))

    def setUsesPeriodicBoundaryConditions(self, periodic):
        return _napshiftforce.NapShiftForce_setUsesPeriodicBoundaryConditions(self, periodic)

    def usesPeriodicBoundaryConditions(self):
        return _napshiftforce.NapShiftForce_usesPeriodicBoundaryConditions(self)

    def setUsesEnsembleAveraging(self, ensembleAveraging):
        return _napshiftforce.NapShiftForce_setUsesEnsembleAveraging(self, ensembleAveraging)

    def usesEnsembleAveraging(self):
        return _napshiftforce.NapShiftForce_usesEnsembleAveraging(self)

    def setRecalculationInterval(self, recalculationInterval):
        return _napshiftforce.NapShiftForce_setRecalculationInterval(self, recalculationInterval)

    def getRecalculationInterval(self):
        return _napshiftforce.NapShiftForce_getRecalculationInterval(self)

    def addPeptide(self, *args):
        return _napshiftforce.NapShiftForce_addPeptide(self, *args)

    def getPeptideParameters(self, *args):
        return _napshiftforce.NapShiftForce_getPeptideParameters(self, *args)

    def setPeptideParameters(self, *args):
        return _napshiftforce.NapShiftForce_setPeptideParameters(self, *args)

    def getNumPeptides(self):
        return _napshiftforce.NapShiftForce_getNumPeptides(self)

    def getAtoms(self):
        return _napshiftforce.NapShiftForce_getAtoms(self)

    def setProperty(self, name, value):
        return _napshiftforce.NapShiftForce_setProperty(self, name, value)

    def getProperties(self):
        return _napshiftforce.NapShiftForce_getProperties(self)

    def setModelType(self, modelType):
        return _napshiftforce.NapShiftForce_setModelType(self, modelType)

    def getModelType(self):
        return _napshiftforce.NapShiftForce_getModelType(self)

    def getKDefaultValue(self):
        return _napshiftforce.NapShiftForce_getKDefaultValue(self)

    def setKDefaultValue(self, defaultK):
        return _napshiftforce.NapShiftForce_setKDefaultValue(self, defaultK)

    def getPytorchModelsDir(self):
        return _napshiftforce.NapShiftForce_getPytorchModelsDir(self)

    def setPytorchModelsDir(self, pytorchModelsDir):
        return _napshiftforce.NapShiftForce_setPytorchModelsDir(self, pytorchModelsDir)

    @staticmethod
    def cast(force):
        return _napshiftforce.NapShiftForce_cast(force)

    @staticmethod
    def isinstance(force):
        return _napshiftforce.NapShiftForce_isinstance(force)
    __swig_destroy__ = _napshiftforce.delete_NapShiftForce

# Register NapShiftForce in _napshiftforce:
_napshiftforce.NapShiftForce_swigregister(NapShiftForce)

